
default: &default
  adapter: oracle_enhanced
  port: 1521
  host: localhost
  username:
  password:

development:
  <<: *default
  database: csc_libray_app_dev
test:
  <<: *default
  database: csc_libray_app_test

production:
  <<: *default
  database: csc_libray_app_prod

