default: &default
  adapter: postgresql
  username:
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: csc_library

production:
  <<: *default
  database: csc_library_production


